### ISSUE TITLE
graba vs reach

### ISSUE THREAD

**Issue by nicotron** [sergiomajluf/Programacion-20172S1#1]
En el commit del [examen](https://github.com/sergiomajluf/Programacion-20172S1/tree/master/Clase%207) usas `PGraphicsPDF pdf;` en el archivo `graba.pde` y en `reach.pde` usas el método más simple solo usando `beginRecord(PDF, "filename.pdf");`  

¿Cual piensas usar para corregir o exigir a los alumnos?  
En mi caso solo estoy pasando el método simple, porque ya se me han fundido más de lo que pueden dar.

**Comment by sergiomajluf** [comment]
Llega tarde mi respuesta, pero llega. Estuve explorando con PDF pero agregaba más complejidad de lo necesario. Opté por saveFrame(), y todos pudieron resolverlo de esa forma.
